# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/elas_libri_256res_mha/echo_asr_ctc_mha_sd0/best_ctc.pth'
  config: 'config/libri/echo_asr_ctc_mha.yaml'
data:
  corpus:
    name:  'Librispeech'
    dev_split: ['dev-clean']
    test_split: ['test-clean']
decode:
  beam_size: 20
  min_len_ratio: 0.01
  max_len_ratio: 0.07
  lm_path: 'ckpt/lm_example_sd0/best_ppx.pth'
  lm_config: 'config/libri/lm_example.yaml'
  lm_weight: 0.5
  ctc_weight: 0.0
